### ISSUE TITLE
New ollama not using gpu

### ISSUE THREAD

**Issue by arpondark** [ollama/ollama#11734]
### What is the issue?

<img width="1627" height="1018" alt="Image" src="https://github.com/user-attachments/assets/6ed1f22e-4f39-4210-ae19-70f203f5121d" /> not using nvdia gpu . using cpu only for every model . without qwen2 model . 

### Relevant log output

```shell
time=2025-08-06T15:57:08.463+06:00 level=INFO source=routes.go:1297 msg="server config" env="map[CUDA_VISIBLE_DEVICES: GPU_DEVICE_ORDINAL: HIP_VISIBLE_DEVICES: HSA_OVERRIDE_GFX_VERSION: HTTPS_PROXY: HTTP_PROXY: NO_PROXY: OLLAMA_CONTEXT_LENGTH:4096 OLLAMA_DEBUG:INFO OLLAMA_FLASH_ATTENTION:false OLLAMA_GPU_OVERHEAD:0 OLLAMA_HOST:http://127.0.0.1:11434 OLLAMA_INTEL_GPU:false OLLAMA_KEEP_ALIVE:5m0s OLLAMA_KV_CACHE_TYPE: OLLAMA_LLM_LIBRARY: OLLAMA_LOAD_TIMEOUT:5m0s OLLAMA_MAX_LOADED_MODELS:0 OLLAMA_MAX_QUEUE:512 OLLAMA_MODELS:C:\\Users\\Administrator\\.ollama\\models OLLAMA_MULTIUSER_CACHE:false OLLAMA_NEW_ENGINE:false OLLAMA_NOHISTORY:false OLLAMA_NOPRUNE:false OLLAMA_NUM_PARALLEL:1 OLLAMA_ORIGINS:[http://localhost https://localhost http://localhost:* https://localhost:* http://127.0.0.1 https://127.0.0.1 http://127.0.0.1:* https://127.0.0.1:* http://0.0.0.0 https://0.0.0.0 http://0.0.0.0:* https://0.0.0.0:* app://* file://* tauri://* vscode-webview://* vscode-file://*] OLLAMA_SCHED_SPREAD:false ROCR_VISIBLE_DEVICES:]"
time=2025-08-06T15:57:08.463+06:00 level=INFO source=images.go:477 msg="total blobs: 0"
time=2025-08-06T15:57:08.463+06:00 level=INFO source=images.go:484 msg="total unused blobs removed: 0"
time=2025-08-06T15:57:08.464+06:00 level=INFO source=routes.go:1350 msg="Listening on 127.0.0.1:11434 (version 0.11.2)"
time=2025-08-06T15:57:08.464+06:00 level=INFO source=gpu.go:217 msg="looking for compatible GPUs"
time=2025-08-06T15:57:08.464+06:00 level=INFO source=gpu_windows.go:167 msg=packages count=1
time=2025-08-06T15:57:08.464+06:00 level=INFO source=gpu_windows.go:183 msg="efficiency cores detected" maxEfficiencyClass=1
time=2025-08-06T15:57:08.464+06:00 level=INFO source=gpu_windows.go:214 msg="" package=0 cores=8 efficiency=4 threads=12
time=2025-08-06T15:57:08.600+06:00 level=INFO source=gpu.go:319 msg="detected OS VRAM overhead" id=GPU-7f06c888-ceb6-9893-d38d-a08e0ffd1954 library=cuda compute=8.9 driver=13.0 name="NVIDIA GeForce RTX 4050 Laptop GPU" overhead="582.2 MiB"
time=2025-08-06T15:57:08.602+06:00 level=INFO source=types.go:130 msg="inference compute" id=GPU-7f06c888-ceb6-9893-d38d-a08e0ffd1954 library=cuda variant=v12 compute=8.9 driver=13.0 name="NVIDIA GeForce RTX 4050 Laptop GPU" total="6.0 GiB" available="5.0 GiB"
```

**Comment by rick-github** [comment]
Add the full server log.

**Comment by arpondark** [comment]
[app-2.log](https://github.com/user-attachments/files/21618032/app-2.log)
[app-3.log](https://github.com/user-attachments/files/21618033/app-3.log)
[app-4.log](https://github.com/user-attachments/files/21618034/app-4.log)
[app-5.log](https://github.com/user-attachments/files/21618037/app-5.log)
[server.log](https://github.com/user-attachments/files/21618038/server.log)
[server-1.log](https://github.com/user-attachments/files/21618043/server-1.log)
[server-2.log](https://github.com/user-attachments/files/21618035/server-2.log)
[server-3.log](https://github.com/user-attachments/files/21618040/server-3.log)
[server-4.log](https://github.com/user-attachments/files/21618042/server-4.log)
[server-5.log](https://github.com/user-attachments/files/21618039/server-5.log)
[app.log](https://github.com/user-attachments/files/21618036/app.log)
[app-1.log](https://github.com/user-attachments/files/21618041/app-1.log)

**Comment by g6w9a** [comment]
My experience with the latest version: Only gpt-oss model (20b) not offloading to GPU, runs on CPU. But other models use gpu without any issue.

**Comment by y-tor** [comment]
Yes, the same behaviour for me

> My experience with the latest version: Only gpt-oss model (20b) not offloading to GPU, runs on CPU. But other models use gpu without any issue.

**Comment by arpondark** [comment]
but in my case only qwen is runnng on gpu llam3 gemma and other not running

**Comment by rnagabhyrava** [comment]
> My experience with the latest version: Only gpt-oss model (20b) not offloading to GPU, runs on CPU. But other models use gpu without any issue.

Same here. Gemma 3 works fine with GPU but gpt-oss is not using GPU at all (6900xt) on v0.11.0/2/3

**Comment by AncientMystic** [comment]
I am having the same issue, except with all models, i tried quite a few and ollama is having issues allocating vram, saying 0b available, saying my gpu doesn't support flash attention, etc 

I had to downgrade to 0.10.1, 11+ just drops my gpu basically. 

(Pascal gen Compute compatibility 6.1 based card)

**Comment by botanegg** [comment]
https://github.com/ollama/ollama/pull/11700

**Comment by JanJohansen** [comment]
Same issue here (on RTX4090). Former version of Ollama worked fine!
Both "Game ready driver" and "Studio Driver" tested. Same issue... So should be Ollama that has the problem.

**Comment by jessegross** [comment]
There was a bug in 0.11.2 and below where the memory estimation would become too high for gpt-oss if the model needed to be split across GPU and CPU or multiple GPUs. This would often cause 100% on CPU usage once the model overflows a single GPU.

This is fixed in 0.11.3.

**Comment by cwiggi01** [comment]
I still have problems, GPT-OSS is pretty bad on my machine compared to LM studio, either runs slowly or not at all, and in LM Studio I get like 150 tokens per second with max context window.
