### ISSUE TITLE
Bug: 500 Internal Server Error: unmarshal: invalid character 'I' with 'kimi-k2-thinking:cloud' model

### ISSUE THREAD

**Issue by TJbarros** [ollama/ollama#13017]
### What is the issue?

Summary
This is a bug report for the kimi-k2-thinking:cloud model endpoint. The ollama.com server is consistently returning a 500 Internal Server Error.

This error response is not valid JSON, which causes the ollama client to fail with an unmarshal error.

🚶 Steps to Reproduce
Run the kimi-k2-thinking:cloud model:

Bash

ollama run kimi-k2-thinking:cloud
After connecting, send any prompt. (I used qual a sua capacidade de programar em python, seja cincero e objetivo ?, but any prompt triggers the error).

💥 Actual Behavior (The Error)
The client immediately prints the following error, indicating a non-JSON response was received from the server.

Connecting to 'kimi-k2-thinking' on 'ollama.com' ⚡
>>> qual a sua capacidade de programar em python, seja cincero e objetivo ?
Error: 500 Internal Server Error: unmarshal: invalid character 'I' looking for beginning of value
🎯 Error Analysis
The key part of the error is: unmarshal: invalid character 'I' looking for beginning of value.

This confirms that the ollama client received a 500 Internal Server Error and the body of that error response was not JSON. The client expected a JSON object (starting with { or [) but instead received a response body starting with the character I.

This is almost certainly a plain-text or HTML error page from the server (e.g., "Internal Server Error" or "Invalid...").

This suggests the kimi-k2-thinking:cloud endpoint is failing and not correctly formatting its error response as a JSON object that the client can understand.

Environment
Ollama Version: ollama version is 0.12.10
OS: Windows / PowerShell

### Relevant log output

```shell

```

**Comment by saibogoo** [comment]
same issues

<img width="547" height="505" alt="Image" src="https://github.com/user-attachments/assets/1ed2ea6d-30eb-4308-9a22-75e854c764f7" />

**Comment by josephlugo** [comment]
Yep

**Comment by rick-github** [comment]
This should be fixed now.

```console
$ ollama run kimi-k2-thinking:cloud hello
...
Hello! How can I help you today?
```

**Comment by saibogoo** [comment]
fixed

**Comment by rick-github** [comment]
It appears this is an intermittent ongoing issue.  The `invalid character 'I'` is a backend error that's causing `Internal Server Error` to be returned, and because it's not properly formed JSON, the local ollama server is throwing a 500.

**Comment by jmorganca** [comment]
It should be fixed now, thanks @rick-github for all the help and everyone who reported! Let me know if you're still seeing the issue

**Comment by kiril1976** [comment]
Error
500 Internal Server Error: unmarshal: invalid character 'I' looking for beginning of value. I still have this mistake and I dont know if this I something wrong with GUI or my MacBook OS Tahoe I use?

**Comment by simmorsal** [comment]
Getting this error when trying to upload an image using Open WebUI. Text works ok.

**Comment by rouk750** [comment]
I'm facing the same error with several cloud models; the latest failure occurred with gpt-oss:120b-cloud.
The same tests worked correctly with models running locally.

**Comment by kiril1976** [comment]
The problem is with Ollama GUI.I try all the models with Docker and Open WebUi and all the models works fine.So I will use them with Open WebUi.But they need to fix the Ollama GUi.

**Comment by rouk750** [comment]
> The problem is with Ollama GUI.I try all the models with Docker and Open WebUi and all the models works fine.So I will use them with Open WebUi.But they need to fix the Ollama GUi.
Not using GUI on my side. I am using langchain to consume model. I am exposing locally ollama through  ollama serve

**Comment by xNeo-git** [comment]
In my case, was solved for kimi-k2-thinking:cloud.
Same error with kimi-k2:1t-cloud.

Thanks!
