### ISSUE TITLE
No response from ollama

### ISSUE THREAD

**Issue by caibirdme** [ollama/ollama#2254]
No response from ollama
```
curl -X POST -d '{"model":"llama2", "messages":[{"role":"user","content":"why the weather in winter is so cold?"}], "stream":false}' 127.0.0.1:11434/api/chat
```

Here's the `ollama list`
```
llama2:latest   78e26419b446    3.8 GB  4 hours ago   
llava:latest    cd3274b81a85    4.5 GB  56 minutes ago
```

And when I use top to see the cpu&mem usage, ollama seems not working, the cpu&mem is very low

**Comment by caibirdme** [comment]
@easp I'm using the latest 0.1.22.
1. `ollama run llama2`, it works.
2. write my own code to access ollama and load llava, it works but after I send some images, it responses `internal error`.
3. Then neither `ollama run` nor curl doesn't work

**Comment by bellowswang** [comment]
Having the same issue.

**Comment by jmorganca** [comment]
This issue should be fixed as of 0.1.25 – but please let me know if it isn't (and if so, would it be possible to share the prompt / image formats you used?) Thanks so much!

**Comment by KUKARAF** [comment]
Issue still present on Debian 12

**Comment by ploncker** [comment]
Issue still present on M1 mac

**Comment by augusto-rehfeldt** [comment]
Issue still present of windows 11 with any model of any size.
