### ISSUE TITLE
have an NVIDIA GPU, but can not use.

### ISSUE THREAD

**Issue by pengyuxiang1** [ollama/ollama#4679]
### What is the issue?

I have an NVIDIA GPU, but why does running the latest script display: "No NVIDIA/AMD GPU detected. Ollama will run in CPU-only mode."? 

The old version of the script had no issues.

I compared the differences between the old and new scripts and found that it might be due to a piece of logic being deleted?

![image](https://github.com/ollama/ollama/assets/38313899/dc6a6dd9-03ce-48a2-bafd-a351274c9a30)

### OS

Linux

### GPU

Nvidia

### Ollama version

0.1.38

**Comment by zimdin12** [comment]
Duplicate downgrade your drivers. it happens after installing Nvidia driver 555.85

**Comment by pengyuxiang1** [comment]
> 降级你的驱动程序。安装 Nvidia 驱动程序 555.85 后就会发生这种情况

This is my NVIDIA version, it is lower than 555.85.

![image](https://github.com/ollama/ollama/assets/38313899/7dcc437f-f58b-4c47-bf0a-f1a54ba30342)

**Comment by lyuehh** [comment]
same problem, driver: 525.105.17, NVIDIA L4, CUDA: 12.0

**Comment by jmorganca** [comment]
This should be fixed now with https://github.com/ollama/ollama/pull/4683, so sorry about that. Re-running the install script should work. Note: Ollama will still use the GPU for you if you ran it previously

**Comment by pengyuxiang1** [comment]
THANKS~

**Comment by pengyuxiang1** [comment]
The good news is: the script is functioning normally.
![image](https://github.com/ollama/ollama/assets/38313899/27a85204-5c1c-49ae-91bc-d5640f9b05b5)

But the bad news is: the ollama program still does not utilize the GPU.

May it is ont only a question of install.sh, still has some other question?
![image](https://github.com/ollama/ollama/assets/38313899/80616b5c-ee46-4ee2-94ba-42227e91baa6)

**Comment by pengyuxiang1** [comment]
The good news is: the script is functioning normally.
![image](https://github.com/ollama/ollama/assets/38313899/d5716f78-42f9-4a0f-aaf6-3e86877d159f)

The bad news is: the current program still does not utilize the GPU.
![image](https://github.com/ollama/ollama/assets/38313899/a063131c-d967-49bf-8bc5-2f9da537dd44)

May it not only be a question of install.sh, but there are still some other questions?
