### ISSUE TITLE
Mistral Small 3

### ISSUE THREAD

**Issue by abenmrad** [ollama/ollama#8697]
Mistral just released a new open weights model that should be close to Llama 3.3 70b in quality. Would be a great addition to the official ollama library!

https://mistral.ai/news/mistral-small-3/
https://huggingface.co/mistralai/Mistral-Small-24B-Base-2501
https://huggingface.co/mistralai/Mistral-Small-24B-Instruct-2501

**Comment by abenmrad** [comment]
Done while I was filing this issue. Thanks again Ollama team!

https://ollama.com/library/[mistral-small](https://ollama.com/library/mistral-small)

**Comment by olumolu** [comment]
Still not showing in the explore section.

**Comment by abenmrad** [comment]
If you mean that it's not featured on the search page, I found it around the middle of the list.

**Comment by olumolu** [comment]
Still not showing 

![Image](https://github.com/user-attachments/assets/103d61a6-cd40-4827-9ecc-815ce2b316fc)
